### ISSUE TITLE
Cannot open ImagePlus because of CacheControls not being passed to BdvFunctions

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/bigdataviewer_scijava#2]
Launching the `OpenImagePlusPlugInSciJavaTest` test class gives the following error:

```
java.lang.ClassCastException: bdv.cache.CacheControl$Dummy cannot be cast to bdv.img.cache.VolatileGlobalCellCache
	at bdv.util.BdvFunctions.show(BdvFunctions.java:205)
	at ch.epfl.biop.bdv.scijava.OpenImagePlusPlugInSciJava.run(OpenImagePlusPlugInSciJava.java:98)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
